
BOARD_WIDTH = 30
BOARD_HEIGHT = 20
INITIAL_SNAKE_LENGTH = 3
INITIAL_SPEED = 0.2  


COLOR_SNAKE = 1  #colro green
COLOR_FOOD = 2   # red
COLOR_BORDER = 3 # white
COLOR_PADDLE = 1
COLOR_BALL = 2 
COLOR_BORDER = 3